LMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^quiz/', include('quiz.urls')),
    path('', include('WebApp.urls')),
    path('forum/',include('forum.urls')),
    path('students/',include('WebApp.student_module.urls')),
    path('teachers/',include('WebApp.teacher_module.urls')),
    path('survey/',include('survey.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebApp/parent_module/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from WebApp.parent_module import views

urlpatterns = (
    # urls for TodoTInfo
    path('', login_required(views.start), name='parent_home'),
)

WebApp/student_module/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required

from WebApp.student_module import views
from survey import views as surveyViews
#
# urlpatterns = (
#     # urls for TodoTInfo
#     path('', login_required(views.start), name='student_home'),
# )
#
#
#

# from django.urls import path
# from . import views

urlpatterns = (
    # urls for TodoTInfo
    path('', login_required(views.start), name='student_home'),
)

urlpatterns += (
    # path('mycourse/', views.mycourse, name="students_mycourse"),
    path('quiz/', views.quiz, name="students_quiz"),
    path('quizzes/', views.quizzes, name="quiz_question"),
    path('calendar/', views.calendar, name="students_calendar"),

)

urlpatterns += (
    # urls for CourseInfo
    path('courseinfo/', views.CourseInfoListView.as_view(),
         name='student_courseinfo_list'),
    path('courseinfo/mycourses', views.MyCoursesListView.as_view(),
         name='student_mycourses_list'),
    path('courseinfo/detail/<int:pk>/', views.CourseInfoDetailView.as_view(),
         name='student_courseinfo_detail'),
)

urlpatterns += (
    # urls for ChapterInfo
    path('courseinfo/<int:course>/chapterinfo/', views.ChapterInfoListView.as_view(), name='student_chapterinfo_list'),
    path('courseinfo/<int:course>/chapterinfo/<int:pk>/', views.ChapterInfoDetailView.as_view(),
         name='student_chapterinfo_detail'),
)

urlpatterns += (
    # urls for AssignmentInfo
    path('courseinfo/<int:course>/chapterinfo/<int:chapter>/assignmentinfo/<int:pk>/',
    views.AssignmentInfoDetailView.as_view(),
        name='student_assignmentinfo_detail'),
    path('myassignments/',views.MyAssignmentsListView.as_view(), name='student_myassignmentinfo_list')
)

urlpatterns += (
    # urls for Profile
    path('profile/', login_required(views.ProfileView),
         name='student_user_profile'),
)

# urlpatterns += (
#     path('questions_student/', views.questions_student, name="questions_student"),
# )
urlpatterns += (
    # urls for SurveyInfo
    path('questions_student/', views.questions_student.as_view(), name='questions_student'),

    path('questions_student_detail/detail/<int:pk>/',
         views.questions_student_detail.as_view(), name='questions_student_detail'),
    
    path('questions_student_detail_history/detail/<int:pk>/',
         views.questions_student_detail_history.as_view(), name='questions_student_detail_history'),

    path('surveyinfo_ajax/', surveyViews.SurveyInfo_ajax.as_view(),
        name='surveyinfo_ajax'),
    
    path('ParticipateSurvey/', views.ParticipateSurvey.as_view(),
        name='ParticipateSurvey'),
        
    path('surveyFilterCategory_student/', views.surveyFilterCategory_student.as_view(),
    name='surveyFilterCategory_student'),

)

# urlpatterns += (
#     path('polls_student/', views.polls_student, name="polls_student"),
# )

# urlpatterns += (
#     path('polls_student_view/', views.polls_student_view,
#          name="polls_student_view"),
# )

WebApp/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

router = routers.DefaultRouter()

# router.register(r'profile', api.ProfileViewSet)
router.register(r'centerinfo', api.CenterInfoViewSet)
router.register(r'memberinfo', api.MemberInfoViewSet)
router.register(r'courseinfo', api.CourseInfoViewSet)
router.register(r'chapterinfo', api.ChapterInfoViewSet)
router.register(r'chaptercontentsinfo', api.ChapterContentsInfoViewSet)
router.register(r'chaptermissoncheckcard', api.ChapterMissonCheckCardViewSet)
router.register(r'chaptermissoncheckitem', api.ChapterMissonCheckItemViewSet)
router.register(r'inninginfo', api.InningInfoViewSet)
router.register(r'sessioninfo', api.SessionInfoViewSet)
# router.register(r'omrquestioninfo', api.OmrQuestionInfoViewSet)
router.register(r'quizinfo', api.QuizInfoViewSet)
router.register(r'assignassignmentinfo', api.AssignAssignmentInfoViewSet)
# router.register(r'assignquestioninfo', api.AssignQuestionInfoViewSet)
router.register(r'boardinfo', api.BoardInfoViewSet)
router.register(r'boardcontentinfo', api.BoardContentInfoViewSet)
router.register(r'inninggroup', api.InningGroupViewSet)
router.register(r'chaptercontentmedia', api.ChapterContentMediaViewSet)
router.register(r'chapterimginfo', api.ChapterImgInfoViewSet)
router.register(r'chaptermissoncheck', api.ChapterMissonCheckViewSet)
router.register(r'chapterwrite', api.ChapterWriteViewSet)
router.register(r'groupmapping', api.GroupMappingViewSet)
router.register(r'assignmentinfo', api.AssignmentInfoViewSet)
router.register(r'learningnote', api.LearningNoteViewSet)
router.register(r'courseubtinfo', api.CourseUbtInfoViewSet)
router.register(r'lessoninfo', api.LessonInfoViewSet)
router.register(r'lessonlog', api.LessonLogViewSet)
router.register(r'membergroup', api.MemberGroupViewSet)
router.register(r'messageinfo', api.MessageInfoViewSet)
# router.register(r'omranswerinfo', api.OmrAnswerInfoViewSet)
# router.register(r'omrassigninfo', api.OmrAssignInfoViewSet)
# router.register(r'omrexampleinfo', api.OmrExampleInfoViewSet)
router.register(r'assignanswerinfo', api.AssignAnswerInfoViewSet)
# router.register(r'qanswerlog', api.QAnswerLogViewSet)
router.register(r'qexampleinfo', api.QExampleInfoViewSet)
router.register(r'questioninfo', api.QuestionInfoViewSet)
router.register(r'quizanswerinfo', api.QuizAnswerInfoViewSet)
router.register(r'quizexampleinfo', api.QuizExampleInfoViewSet)
router.register(r'scheduleinfo', api.ScheduleInfoViewSet)
router.register(r'talkmember', api.TalkMemberViewSet)
router.register(r'talkroom', api.TalkRoomViewSet)
router.register(r'talkmessage', api.TalkMessageViewSet)
router.register(r'talkmessageread', api.TalkMessageReadViewSet)
router.register(r'todoinfo', api.TodoInfoViewSet)
router.register(r'todotinfo', api.TodoTInfoViewSet)

urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
    url(r'^$', views.start, name='start'),
    url(r'^login/$', views.login, {'template_name': 'registration/login.html',
                                   'redirect_authenticated_user': True}, name='login'),

    url(r'^.*logout/$', views.logout,
        {'template_name': 'registration/logout.html', 'next_page': '/'}, name='logout'),

    url(r'^.*editprofile/$', views.editprofile, name='editprofile'),

    url(r'^successlogin/$', views.loginsuccess, name='loginsuccess'),

    url(r'^.*register/$', views.register.as_view(), name='register'),
)

# urlpatterns += (
#     # urls for Profile
#     path('profile/', views.ProfileListView.as_view(), name='profile_list'),
#     path('profile/create/', views.ProfileCreateView.as_view(), name='profile_create'),
#     path('profile/detail/<int:pk>/', views.ProfileDetailView.as_view(), name='profile_detail'),
#     path('profile/update/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile_update'),
# )

urlpatterns += (
    # urls for Profile
    path('profile/', login_required(views.ProfileView), name='user_profile'),
    path('change-password/', views.PasswordChangeView.as_view(
        template_name='registration/change_password.html')),
    path('change-password/<int:pk>/', views.change_password_others),
)

urlpatterns += (
    # urls for CenterInfo
    path('centerinfo/', login_required(views.CenterInfoListView.as_view()),
         name='centerinfo_list'),
    path('centerinfo/create/', login_required(views.CenterInfoCreateView.as_view()),
         name='centerinfo_create'),
    path('centerinfo/detail/<int:pk>/',
         views.CenterInfoDetailView.as_view(), name='centerinfo_detail'),
    path('centerinfo/update/<int:pk>/',
         views.CenterInfoUpdateView.as_view(), name='centerinfo_update'),
    path('centerinfo/delete/<int:pk>/',
         views.CenterInfoDeleteView, name='centerinfo_delete'),
    # url(r'^deletethread/(?P<pk>\d+)/$', views.thread_delete, name='smart_forum_thread_delete'),

)

urlpatterns += (
    # urls for MemberInfo
    path('memberinfo/', views.MemberInfoListView.as_view(), name='memberinfo_list'),
    path('memberinfo/inactive', views.MemberInfoListViewInactive.as_view(), name='memberinfo_list_inactive'),
    path('memberinfo/create/', views.MemberInfoCreateView.as_view(), name='memberinfo_create'),
    path('memberinfo/detail/<int:pk>/', views.MemberInfoDetailView.as_view(), name='memberinfo_detail'),
    path('memberinfo/update/<int:pk>/', views.MemberInfoUpdateView.as_view(), name='memberinfo_update'),
    path('memberinfo/delete/<int:pk>/', views.MemberInfoDeleteView.as_view(), name='memberinfo_delete'),
)

urlpatterns += (
    # urls for CourseInfo
    path('courseinfo/', views.CourseInfoListView.as_view(), name='courseinfo_list'),
    path('courseinfo/create /', views.CourseInfoCreateView.as_view(), name='courseinfo_create'),
    path('courseinfo/<int:pk>/', views.CourseInfoDetailView.as_view(), name='courseinfo_detail'),
    path('courseinfo/edit/<int:pk>/', views.CourseInfoUpdateView.as_view(), name='courseinfo_update'),
)

urlpatterns += (
    # urls for ChapterInfo
    path('chapterinfo/create/ajax', views.ChapterInfoCreateViewAjax.as_view(), name='chapterinfo_create_ajax'),
    path('courseinfo/<int:course>/chapterinfo/', views.ChapterInfoListView.as_view(), name='chapterinfo_list'),
    path('courseinfo/<int:course>/create/', views.ChapterInfoCreateView.as_view(), name='chapterinfo_create'),
    path('courseinfo/<int:course>/chapterinfo/<int:pk>/', views.ChapterInfoDetailView.as_view(), name='chapterinfo_detail'),
    path('courseinfo/<int:course>/chapterinfo/<int:pk>/edit/', views.ChapterInfoUpdateView.as_view(), name='chapterinfo_update'),
    path('courseinfo/<int:course>/forum/' , views.CourseForum.as_view(), name='Course_Forum'),
)

urlpatterns += (
    # urls for ChapterContentsInfo
    path('chaptercontentsinfo/', views.ChapterContentsInfoListView.as_view(),
         name='chaptercontentsinfo_list'),
    path('chaptercontentsinfo/create/', views.ChapterContentsInfoCreateView.as_view(),
         name='chaptercontentsinfo_create'),
    path('chaptercontentsinfo/detail/<int:pk>/', views.ChapterContentsInfoDetailView.as_view(),
         name='chaptercontentsinfo_detail'),
    path('chaptercontentsinfo/update/<int:pk>/', views.ChapterContentsInfoUpdateView.as_view(),
         name='chaptercontentsinfo_update'),
)

urlpatterns += (
    # urls for ChapterMissonCheckCard
    path('chaptermissoncheckcard/', views.ChapterMissonCheckCardListView.as_view(),
         name='chaptermissoncheckcard_list'),
    path('chaptermissoncheckcard/create/', views.ChapterMissonCheckCardCreateView.as_view(),
         name='chaptermissoncheckcard_create'),
    path('chaptermissoncheckcard/detail/<int:pk>/', views.ChapterMissonCheckCardDetailView.as_view(),
         name='chaptermissoncheckcard_detail'),
    path('chaptermissoncheckcard/update/<int:pk>/', views.ChapterMissonCheckCardUpdateView.as_view(),
         name='chaptermissoncheckcard_update'),
)

urlpatterns += (
    # urls for ChapterMissonCheckItem
    path('chaptermissoncheckitem/', views.ChapterMissonCheckItemListView.as_view(),
         name='chaptermissoncheckitem_list'),
    path('chaptermissoncheckitem/create/', views.ChapterMissonCheckItemCreateView.as_view(),
         name='chaptermissoncheckitem_create'),
    path('chaptermissoncheckitem/detail/<int:pk>/', views.ChapterMissonCheckItemDetailView.as_view(),
         name='chaptermissoncheckitem_detail'),
    path('chaptermissoncheckitem/update/<int:pk>/', views.ChapterMissonCheckItemUpdateView.as_view(),
         name='chaptermissoncheckitem_update'),
)

# urlpatterns += (
#     # urls for OmrQuestionInfo
#     path('omrquestioninfo/', views.OmrQuestionInfoListView.as_view(), name='omrquestioninfo_list'),
#     path('omrquestioninfo/create/', views.OmrQuestionInfoCreateView.as_view(), name='omrquestioninfo_create'),
#     path('omrquestioninfo/detail/<int:pk>/', views.OmrQuestionInfoDetailView.as_view(), name='omrquestioninfo_detail'),
#     path('omrquestioninfo/update/<int:pk>/', views.OmrQuestionInfoUpdateView.as_view(), name='omrquestioninfo_update'),
# )

urlpatterns += (
    # urls for QuizInfo
    path('quizinfo/', views.QuizInfoListView.as_view(), name='quizinfo_list'),
    path('quizinfo/create/', views.QuizInfoCreateView.as_view(),
         name='quizinfo_create'),
    path('quizinfo/detail/<int:pk>/',
         views.QuizInfoDetailView.as_view(), name='quizinfo_detail'),
    path('quizinfo/update/<int:pk>/',
         views.QuizInfoUpdateView.as_view(), name='quizinfo_update'),
)

urlpatterns += (
    # urls for HomeworkInfo
    path('assignmentinfo/create/ajax', views.AssignmentInfoCreateViewAjax.as_view(), name='assignmentinfo_create_ajax'),

    path('courseinfo/<int:course>/chapterinfo/<int:chapter>/assignmentinfo/', views.AssignmentInfoListView.as_view(),

forum/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from django.urls import path
from . import api
from . import views

app_name = "forum"
api_router = routers.DefaultRouter()
router = routers.DefaultRouter()
router.register(r'thread', api.ThreadViewSet)
router.register(r'post', api.PostViewSet)
router.register(r'notification', api.NotificationViewSet)
router.register(r'nodegroup', api.NodeGroupViewSet)
router.register(r'topic', api.TopicViewSet)

urlpatterns = [
    path(r'^page/(?P<page>[0-9]+)/$', views.Index.as_view(), name='index'),
    path(r'', views.Index.as_view(), name='index'),
    path(r'^topic/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$',
         views.TopicView.as_view(), name='topic'),
    path('topic/<int:pk>/', views.TopicView.as_view(), name='topic'),
    path(r'^nodegroup/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$',
         views.NodeGroupView.as_view(), name='nodegroup'),
    path('nodegroup/<int:pk>/', views.NodeGroupView.as_view(), name='nodegroup'),
    path(r't/edit/<int:pk>/', views.edit_thread, name='edit_thread'),
    path(r'post/edit/<int:pk>/', views.edit_post, name='edit_post'),
    path(r'topic/edit/<int:pk>/', views.edit_topic, name='edit_topic'),
    path(r't/append/<int:pk>/', views.create_appendix, name='create_appendix'),
    path(r'^t/(?P<pk>\d+)/page/(?P<page>[0-9]+)/$',
         views.ThreadView.as_view(), name='thread'),
    path(r't/<int:pk>/', views.ThreadView.as_view(), name='thread'),
    path(r'u/<int:pk>/', views.user_info, name='user_info'),
    path(r'^u/(?P<pk>\d+)/threads/page/(?P<page>[0-9]+)/$',
         views.UserThreads.as_view(), name='user_threads'),
    path(r'u/threads/<int:pk>/', views.UserThreads.as_view(), name='user_threads'),
    path(r'^u/(?P<pk>\d+)/posts/page/(?P<page>[0-9]+)/$',
         views.UserPosts.as_view(), name='user_posts'),
    path(r'u/posts/<int:pk>/', views.UserPosts.as_view(), name='user_posts'),
    path(r'login/', views.login_view, name='login'),
    path(r'reg/', views.reg_view, name='reg'),
    path(r'logout/', views.logout_view, name="logout"),
    path(r'search/', views.search_redirect, name='search_redirect'),
    path(r'^search/(?P<keyword>.*?)/page/(?P<page>[0-9]+)/$',
         views.SearchView.as_view(), name='search'),
    path(r'search/(?P<keyword>.*)/', views.SearchView.as_view(), name='search'),
    path(r't/create/', views.create_thread, name='create_thread'),
    path(r't/create/(?P<nodegroup_pk>\d+)/',
         views.create_thread, name='create_thread'),
    path(r't/create/(?P<nodegroup_pk>\d+)/(?P<topic_pk>\d+)/',
         views.create_thread, name='create_thread'),
    path(r'topic/create/', views.create_topic, name='create_topic'),
    path(r'topic/create/(?P<nodegroup_pk>\d+)',
         views.create_topic, name='create_topic'),
    path(r'notifications/', views.NotificationView.as_view(), name='notifications'),
    path(r'avatar/', views.upload_avatar, name="upload_avatar"),
    path(r'api/v1/', include(router.urls)),
]

WebApp/parent_module/views.py
from django.shortcuts import render


def start(request):
    """Start page with a documentation.
    """
    # return render(request,"start.html")
    return render(request, "parent_module/homepage.html")

WebApp/templates/WebApp/theme/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="text-center errorMessage" id="message">
            <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    ERROR
                {% else %}
                    {{ message.tags|title }}
                {% endif %}
            </strong>
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}





{#{% if form.non_field_errors %}#}
{##}
{#    {% for error in form.non_field_errors %}#}
{##}
{##}
{#        <div class="alert alert-danger alert-dismissible fade show" role="alert">#}
{#           <strong> {{ error }} </strong>#}
{#            <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                <span aria-hidden="true">&times;</span>#}
{#            </button>#}
{#        </div>#}
{##}
{#    {% endfor %}#}
{##}
{#{% endif %}#}

WebApp/templates/WebApp/theme/footer.html
<hr>
<footer>

    <div class="pull-right">

        <p id="footerText"><b> Copyright (C) 2019 NSDevil ALL RIGHTS RESERVED </b> </p>

    </div>

    {#    <div class="clearfix"></div>#}
</footer>

WebApp/templates/WebApp/theme/sidebar.html
{% load static %}
<div class="left_col scroll-view">


    <!-- menu profile quick info -->


    <div class="navbar nav_title" style="border: 0;">
        <a href="/" class="site_title"><img src="/static/images/logo.png" alt="..." id="ubl_logo"/>
            <span id="LMS">u-LMS 2019</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->

    <div class="profile clearfix">
        {% if request.user.is_authenticated %}
            <div class="profile_pic">
                <img src="
                        {% if request.user.Member_Avatar %}
                            {{ request.user.Member_Avatar.url }}
                        {% elif request.user.Member_Gender == '1' %}
                            {% static 'images/profile/male.jpg' %}
                        {% elif request.user.Member_Gender == '2' %}
                            {% static 'images/profile/female.png' %}
                        {% else %}
                            {% static 'images/profile/profile.png' %}
                        {% endif %}"
                alt="..." class="img-circle profile_img" />
        </div>

        <div class="profile_info">

            <span>Welcome,</span>
            <h2>{{ request.user.username }}</h2>
        </div>
        {% endif %}
    </div>
    <!-- /menu profile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            {% if user.is_authenticated %}

                <h3>Admin Portal Home</h3>

                <hr>

                <ul class="nav side-menu">
                    <li>
                        <a href="/"><i class="fa fa-home"></i> Dashboard
                        </a>


                    </li>
                    <li>
                        <a href="{% url 'admin_calendar' %}"><i class="fa fa-calendar"></i> Calendar
                        </a>
                    </li>
                    <li>
                        <a><i class="fa fa-user"></i>Members<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{% url 'memberinfo_list' %}">Members List</a></li>
                            <li>
                                <a href="{% url 'memberinfo_create' %}">Create New Member</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-book"></i> Courses
                            <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{% url 'courseinfo_list' %}">Course List</a></li>
                            <li>
                                <a href="{% url 'courseinfo_create' %}">Create New Course</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a ><i class="fa fa-question"></i> Quiz <span class="fa fa-chevron-down"></span>
                        </a>
                        <ul class="nav child_menu"> 
                                <li><a href="{% url 'quiz_list' %}">Quiz List</a></li>
                                <li><a href="{% url 'quiz_progress' %}">Progress Page</a></li>
                                <li>
                                    <a href="{% url 'quiz_marking' %}">Marking Page</a>
                                </li>
                            </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-list"></i> Session
                            <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{% url 'sessioninfo_list' %}">List of Sessions</a></li>
                            <li><a href="{% url 'groupmapping_list' %}">Batch Registration</a></li>
                            <li><a href="{% url 'inninggroup_list' %}">Assign Course to Teacher</a></li>
                            <li><a href="{% url 'inninginfo_list' %}">Sessions Mapping</a></li>
                        </ul>
                    </li>



                </ul>
            {% endif %}

            <hr>
            <ul class="nav side-menu">
                <li>
                    <a><i class="fa fa-user"></i>Forum<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{% url 'forum:index' %}">Home</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'forum:user_info' request.user.pk %}">profile</a></li>
                        {% endif %} {% for nodegroup in node_groups %}
                        <li><a href="{% url 'forum:nodegroup' nodegroup.pk %}">{{ nodegroup.title }}</a></li>
                        {% endfor %}

                    </ul>
                </li>

                <li>
                    <a href="{% url 'messageinfo_list' %}">
                        <i class="fa fa-envelope" id="messageSidebar"></i>Message</a>
                </li>
                <li>
                    <a href=" {% url 'surveyinfo_list' %}"><i class="fa fa-bar-chart"></i>Survey</a>
                </li>
            </ul>
        </div>

    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>